def cyrtolat(string):
    if not isinstance(string, str):
        return string
    switch = {
        'љ':'lj',
        'њ':'nj',
        'е':'e',
        'р':'r',
        'т':'t',
        'ѕ':'dz',
        'у':'u',
        'и':'i',
        'о':'o',
        'п':'p',
        'а':'a',
        'с':'s',
        'д':'d',
        'ф':'f',
        'г':'g',
        'х':'h',
        'ј':'j',
        'к':'k',
        'л':'l',
        'ч':'ch',
        'ш':'sh',
        'ѓ':'gj',
        'ќ':'kj',
        'ж':'zh',
        'з':'z',
        'џ':'dzh',
        'ц':'c',
        'в':'v',
        'б':'b',
        'н':'n',
        'м':'m',
        
        'Љ':'Lj',
        'Њ':'Nj',
        'Е':'E',
        'Р':'R',
        'Т':'T',
        'Ѕ':'Dz',
        'У':'U',
        'И':'I',
        'О':'O',
        'П':'P',
        'А':'A',
        'С':'S',
        'Д':'D',
        'Ф':'F',
        'Г':'G',
        'Х':'H',
        'Ј':'J',
        'К':'K',
        'Л':'L',
        'Ч':'Ch',
        'Ш':'Sh',
        'Ѓ':'Gj',
        'Ќ':'Kj',
        'Ж':'Zh',
        'З':'Z',
        'Џ':'Dzh',
        'Ц':'C',
        'В':'V',
        'Б':'B',
        'Н':'N',
        'М':'M',

        '-':'-' # they may look the same, but one is unicode and that breaks the application lmao
    }
    retStr = ""
    for i in range(len(string)):
        retStr += switch.get(string[i], string[i])
    return retStr